name: Leaky CI

on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: echo "${{ secrets.API_KEY }}"
      - name: hardcoded token
        env:
          API_TOKEN: ghp_1234567890abcdefghijklmnopqrstuvwxyzAB
        run: npm test
